### ISSUE TITLE
Error: Refresh access token failed with status code: 400

### ISSUE THREAD

**Issue by Stevebbu** [microsoft/BotBuilder-V3#176] opened 2019-12-29 01:17 UTC
My bot stop working and seeing the log I've found the following message:

```
Error: Refresh access token failed with status code: 400
```
The appId and password are OK.

## Version
3.16.0

**Comment by EricDahlvang** [comment] 2019-12-29 07:32
Hi @Stevebbu 

Please share the bot handle or Microsoft App Id for the bot.

Also, please check the secrect of the app registration, to ensure it does not have an expiration date.

**Comment by EricDahlvang** [comment] 2020-01-01 00:04
Also, please try upgrading to the last v3 version: https://www.nuget.org/packages/Microsoft.Bot.Builder/3.20.1  There should be no breaking changes.

**Comment by scheyal** [comment] 2020-01-13 19:04
The issue is resolved. Closing.

**Closed by scheyal** 2020-01-13 19:04 UTC
Labels: Bot Services, customer-replied-to, customer-reported
