### ISSUE TITLE
Bot not sending Welcome Message first time

### ISSUE THREAD

**Issue by clari182** [Microsoft/BotBuilder-V3#71] opened 2018-11-19 19:23 UTC
## Version
V3

## Describe the bug
I'm using the ActivityType Conversation Update to send a welcome message to the user.
This was working fine until now, where the bot doesn't send the message the first time anymore. (Neither on the Emulator or in the Web Chat)

This is the code 
```c#
            else if (messageType == ActivityTypes.ConversationUpdate)
            {
                // Handle conversation state changes, like members being added and removed
                // Use Activity.MembersAdded and Activity.MembersRemoved and Activity.Action for info
                // Not available in all channels
                IConversationUpdateActivity iConversationUpdated = message as IConversationUpdateActivity;
                if (iConversationUpdated != null)
                {
                    ConnectorClient connector = new ConnectorClient(new System.Uri(message.ServiceUrl));

                    foreach (var member in iConversationUpdated.MembersAdded ?? System.Array.Empty<ChannelAccount>())
                    {
                        // if the bot is added, then 
                        if (member.Id == iConversationUpdated.Recipient.Id)
                        {
                            var reply = ((Activity)iConversationUpdated).CreateReply(Properties.Messages.welcome_message);
                            await connector.Conversations.ReplyToActivityAsync(reply);
                        }
                    }
                }
            }
```
When I run the bot on the Emulator and debug the code, it looks like it works fine but no message is sent on the emulator.
When I reload the bot on the emulator (not restarting the app, just clicking on the reload button), the message is sent correctly.

The same behavior happens on the DirectLine (when loading the page the first time, nothing happens, but after reloading, the message is sent correctly.)

How can I fix this?

Thanks!

[bug]
[dotnet]

**Comment by EricDahlvang** [comment] 2018-11-20 23:54
Hi @clari182 

This is a known issue with a workaround described here: https://blog.botframework.com/2018/07/12/how-to-properly-send-a-greeting-message-and-common-issues-from-customers/

There is also a related issue on the WebChat repository:
https://github.com/Microsoft/BotFramework-WebChat/issues/1371

I'm closing this issue, since this is the BotBuilder-V3 sdk repository and the issue is more related to WebChat or the Emulator.  Please follow https://github.com/Microsoft/BotFramework-WebChat/issues/1371 for progress on the fix.

**Closed by EricDahlvang** 2018-11-20 23:54 UTC
