### ISSUE TITLE
Formflow: Acts as though it is on the previous step 

### ISSUE THREAD

**Issue by PaulPreteau** [Microsoft/BotBuilder-V3#100] opened 2018-12-25 19:55 UTC
## Version
3.15.2.2

## Describe the bug
When going through Formflow occasionally it acts as though it is on the previous question.

## To Reproduce
1. Create a TEAMS formflow bot with multiple enum fields
2. allow the user to answer with sub-strings
3. Deploy to Azure
4. Go back and forth between fields (this bug dosen't happen frequenly.)
5. See error

## Expected behavior
I expect it to always accept an answer

## Screenshots
![image](https://user-images.githubusercontent.com/41088701/50426049-2f8eca80-084a-11e9-81d9-ca7ff01de196.png)

[bug]
[dotnet]

**Comment by v-kydela** [comment] 2018-12-27 00:08
Hi Paul. Can you please let us know if you can reproduce the problem locally using the Bot Emulator? If it's only in a deployed bot and only in Teams, that would be a very strange bug indeed.

I wonder if it's related to a FormFlow [bug](https://github.com/Microsoft/BotBuilder-V3/issues/99) I recently posted about partial matches on the navigation step. Your enum fields present a list of choices in a similar way to the navigation step. You say the bug doesn't happen frequently, so could you perhaps do a bit of testing to determine the exact conditions where the bug can be reproduced reliably? If you can't quite pin it down then could you still provide the code for a minimal and verifiable example? I'd like to test this but I need some more information first.

**Comment by PaulPreteau** [comment] 2018-12-28 02:14
I have reproduced it on the emulator and have created simplified code, which the issue happened again with.

here is the code (it is based on a luis bot)
luisBot

    using System.Net.Http;
    using System.Threading;
    using System.Collections.Generic;
    
    using Microsoft.Bot.Connector;
    using Microsoft.Bot.Builder.Dialogs;
    using Microsoft.Bot.Builder.Luis;
    using Microsoft.Bot.Builder.Luis.Models;
    using Microsoft.Bot.Sample.LuisBot.HelperClasses;
    using Microsoft.Bot.Sample.LuisBot.Dialogs;
    using LuisBot.Dialogs;
    using System.Linq;
    
    namespace Microsoft.Bot.Sample.LuisBot
    {

        [LuisModel("", "")] //LUIS App ID and API Key respectively.
        [Serializable]
        public class LuisDialog : LuisDialog<object>
        {
    
            public LuisDialog()
            {
            }

            // Go to https://luis.ai and create a new intent, then train/publish your luis app.
            // Finally replace "Greeting" with the name of your newly created intent in the following handler
            [LuisIntent("Greeting")]
            public async Task GreetingIntent(IDialogContext context, LuisResult result)
            {
                await context.PostAsync($"Hello, {context.Activity.From.Name}");
    
                AskHelp(context);
            }
    
            [LuisIntent("Cancel")]
            public async Task CancelIntent(IDialogContext context, LuisResult result)
            {
                await context.PostAsync($"Goodbye {context.Activity.From.Name}, and thank you for using Aria Self Service!");
    
                context.Done("End Conversation");
            }

            [LuisIntent("Help")]
            public async Task HelpIntent(IDialogContext context, LuisResult result)
            {
    
                await context.Forward(new TestFormDialog(), ResumeAfterDialog, result, CancellationToken.None);
            }
        }
    }

dialog
        
    using Microsoft.Bot.Builder.Dialogs;
    using Microsoft.Bot.Builder.FormFlow;
    using Microsoft.Bot.Builder.Luis.Models;
    
    using Microsoft.Bot.Sample.LuisBot.FormFlow;
    using Microsoft.Bot.Sample.LuisBot.WebService;
    using Microsoft.Bot.Sample.LuisBot.HelperClasses;
    
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Net;
    using System.Net.Http;
    using System.Net.Http.Headers;
    using System.Threading.Tasks;
    using System.Web.Mvc;
    using LuisBot.FormFlow;
    
    namespace LuisBot.Dialogs
    {
        [Serializable]
        public class TestFormDialog : IDialog
        {
            private static IEnumerable<SelectListItem> choice1;
            private static IEnumerable<SelectListItem> choice2;
    
            public async Task StartAsync(IDialogContext context)
            {
    
                try
                {
                    context.Wait<LuisResult>(ItemReceived);
                }
                catch(Exception e)
                {
                    var message = e.Message;
                    await context.PostAsync(message);
                }
            }
    
            public async Task ItemReceived(IDialogContext context, IAwaitable<LuisResult> item)
            {
                await item;
    
                await context.PostAsync("Getting Options, please wait while I set things up for you....");
    
                GetChoices();
    
                context.Call<TestForm>(await GetTestFormAsync(context), ResumeAfterTestFormAsync);
            }
    
            private async Task ResumeAfterTestFormAsync(IDialogContext context, IAwaitable<TestForm> result)
            {
                try
                {
                    TestForm results = await result;
    
                    await context.PostAsync("Submitting your Request...");
                }
                catch(FormCanceledException<TestForm> e)
                {
                    string reply;
                    if(e.InnerException == null)
                    {
                        reply = $"You quit on {e.Last}";
                    }
                    else
                    {
                        reply = $"An unexpected Error has occured with error message of: {e.Message} -- for support please contact: DevOps-IntOps@varian.com";
                    }
                    await context.PostAsync(reply);
                }
                catch(Exception e)
                {
                    await context.PostAsync($"An unexpected Error has occured with error message of: {e.Message} -- for support please contact: DevOps-IntOps@varian.com");
                }
    
                context.Done("Test");
            }
    
            private async Task<IFormDialog<TestForm>> GetTestFormAsync(IDialogContext context)
            {
    
                FormDialog<TestForm> formDialog =
                new FormDialog<TestForm>
                    (new TestForm(), TestForm.BuildForm, FormOptions.PromptInStart);
    
                return formDialog;
            }
    
            private void GetChoices()
            {
                List<SelectListItem> choices1 = new List<SelectListItem>();
                choices1.Add(new SelectListItem() { Text = "aaa"});
                choices1.Add(new SelectListItem() { Text = "bbb"});
                choices1.Add(new SelectListItem() { Text = "ccc"});
                choice1 = choices1;
    
                List<SelectListItem> choices2 = new List<SelectListItem>();
                choices2.Add(new SelectListItem() { Text = "ddd" });
                choices2.Add(new SelectListItem() { Text = "eee" });
                choices2.Add(new SelectListItem() { Text = "fff" });
                choice2 = choices2;
            }
    
            public static async Task<IEnumerable<SelectListItem>> GetChoice1()
            {
                return choice1;
            }
    
            public static async Task<IEnumerable<SelectListItem>> GetChoice2()
            {
                return choice2;
            }
        }
    }

Form

    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Threading.Tasks;
    
    using Microsoft.Bot.Builder.FormFlow;
    using Microsoft.Bot.Builder.FormFlow.Advanced;
    using Microsoft.Bot.Connector;
    using Microsoft.Bot.Sample.LuisBot.Dialogs;
    using System.Web.Mvc;
    using LuisBot.Dialogs;
    
    namespace LuisBot.FormFlow
    {
        [Serializable]
        public class TestForm
        {
            public string Choice1;
    
            public string Choice2;
    
            public static IForm<TestForm> BuildForm()
            {
                var form = new FormBuilder<TestForm>()
                    .Message("I have created your request form, please answer the following questions.")
                    .Field(new FieldReflector<TestForm>(nameof(Choice1))
                        .SetType(null)
                        .SetActive((state) => true)
                        .SetDefine(async (state, field) =>
                        {
                            await DefineChoice1Async(field);
                            return await Task.FromResult(true);
                        }))
                    .Field(new FieldReflector<TestForm>(nameof(Choice2))
                        .SetType(null)
                        .SetActive((state) => true)
                        .SetDefine(async (state, field) =>
                        {
                            await DefineChoice2Async(field);
                            return await Task.FromResult(true);
                        }))
                    .Confirm(async (state) =>
                    {
                        return new PromptAttribute($"You have selected the following:\n" +
                            $"Organization: {state.Choice1}\n" +
                            $"Domain: {state.Choice2}\n" +
                            "Is this correct? (yes submits environment request){||}");
                    });
    
                var command = form.Configuration.Commands[FormCommand.Quit];
                var terms = command.Terms.ToList();
                terms.Add("cancel");
                terms.Add("exit");
                command.Terms = terms.ToArray();
    
                return form.Build();
            }
    
            private static async Task DefineChoice1Async(Field<TestForm> field)
            {
                System.Diagnostics.Trace.TraceInformation("define");
                IEnumerable<SelectListItem> organizationObjects = await TestFormDialog.GetChoice1();
    
                SetFieldDescriptionAndTerms(field, organizationObjects);
            }
    
            private static async Task DefineChoice2Async(Field<TestForm> field)
            {
                IEnumerable<SelectListItem> domainObjects = await TestFormDialog.GetChoice2();
    
                SetFieldDescriptionAndTerms(field, domainObjects);
            }
    
            private static void SetFieldDescriptionAndTerms(Field<TestForm> field, IEnumerable<SelectListItem> selectListItems)
            {
                field.SetRecognizer(new TestFormRecognizer<TestForm>(field));
    
                foreach(var item in selectListItems)
                {
                    field
                        .AddDescription(item.Text, item.Text)
                        .AddTerms(item.Text, item.Text);
                }
            }
        }
    
        internal class TestFormRecognizer<T> : IRecognize<T>
        {
            private Field<TestForm> field;
    
            public TestFormRecognizer(Field<TestForm> field)
            {
                this.field = field;
            }
    
            public string Help(T state, object defaultValue = null)
            {
                string help = $"You can enter a number from 1-{field.Values.Count()} or words from the descriptions: ";
                foreach(DescribeAttribute attribute in field.ValueDescriptions)
                {
                    help += attribute.Description;
    
                    if(attribute.Equals(field.ValueDescriptions.Last()))
                    {
                        help += ".";
                    }
                    else
                    {
                        help += ", ";
                    }
                }
    
                return help;
            }
    
            public IEnumerable<TermMatch> Matches(IMessageActivity input, object defaultValue = null)
            {
                var values = field.Values;
                List<TermMatch> matches = null;
                bool exactMatch = false;
                int index = -1;
    
    
                //check if user enterd a number indicating their selection else check for substring
                if(int.TryParse(input.Text, out index) && index > 0 && index <= values.Count())
                {
                    matches = new List<TermMatch>();
                    matches.Add(new TermMatch(0, input.Text.Length, 1.0, values.ElementAt(index - 1)));
                }
                else
                {
                    matches = new List<TermMatch>();
                    foreach(object value in values)
                    {
                        if(field.ValueDescription(value).Description.ToLower().Equals(input.Text.ToLower()))
                        {
                            exactMatch = true;
    
                            matches = new List<TermMatch>
                            {
                                new TermMatch(0, input.Text.Length, 1.0, value)
                            };
                        }
                        else if(!exactMatch && field.ValueDescription(value).Description.ToLower().Contains(input.Text.ToLower()))
                        {
                            matches.Add(new TermMatch(0, input.Text.Length, 1.0, value));
                        }
                    }
                }
    
                return matches;
            }
    
            public object[] PromptArgs()
            {
                return null;
            }
    
            public IEnumerable<string> ValidInputs(object value)
            {
                List<string> inputs = new List<string>
                {
                    field.ValueDescription(value).Description
                };
    
                return inputs;
            }
    
            public DescribeAttribute ValueDescription(object value)
            {
                return field.ValueDescription(value);
            }
    
            public IEnumerable<DescribeAttribute> ValueDescriptions()
            {
                return field.ValueDescriptions;
            }
    
            public IEnumerable<object> Values()
            {
                return field.Values;
            }
        }
    }
    
Here is a screenshot of it happening:
![image](https://user-images.githubusercontent.com/41088701/50499597-73333100-0a10-11e9-83a6-8167427e12fb.png)

**Comment by v-kydela** [comment] 2018-12-30 03:41
I'm afraid even with your code I still can't reproduce the issue. If you want further help I think it would be a good idea to include repro steps. You might also consider trying to debug it yourself by setting breakpoints in your delegates. And if you want to get really advanced you could define a [prompter](https://github.com/v-kydela/BotBlog/blob/master/Blog%20-%20Making%20your%20own%20Prompter.md) and set a breakpoint in that because then you'd be able to verify what step FormFlow thinks it's on.

This very well may be a FormFlow bug. But even if you can gather more information about it, this isn't the kind of bug that will be fixed in V3. If you'd like to try V4, there is actually a way to use FormFlow in V4 now: https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/tree/master/libraries/Bot.Builder.Community.Dialogs.FormFlow

**Comment by PaulPreteau** [comment] 2019-01-02 20:57
I updated the framework to 3.19.1.44133 and this seems to have solved the issue.

**Comment by v-kydela** [comment] 2019-01-02 20:58
Glad to hear it, @PaulPreteau !

**Closed by v-kydela** 2019-01-02 20:58 UTC
