### ISSUE TITLE
Unable to save Kik channel configuration

### ISSUE THREAD

**Issue by InsaneNaman** [Microsoft/BotBuilder-V3#81] opened 2018-12-01 17:51 UTC
* SDK Platform: Node.js
* SDK Version: 3.x.x
* Deployment Environment: Bot Channel Registeration Service
* Issue Description
* Cannot Save Kik Channel Configuration

###  Reproduction Steps
1-Goto Azure Portal
2-Select Bot App
3-Channels
4- Kik
5- Add Credentials (Display Name and Token)
6- Save
### Expected Behavior
Save and Enable Kik Channel

### Actual Results
Unable to save. Failed to register with: BadRequest ID: 

### Screenshot
![sketch1543672334363](https://user-images.githubusercontent.com/13780776/49331173-13876880-f5bf-11e8-92f9-c5e8fdf13bb1.png)

### Other
Messenger and Telegram are working but Kik configuration page is throwing an error. I've tried to connect bot with kik through a different Bot Service in Azure but getting the same error.

**Comment by EricDahlvang** [comment] 2018-12-03 21:17
Hi @InsaneNaman 

Are you using the bot's Display Name, or your personal Display Name?  

This placeholder text should state: "Your bot's Kik display name"

![image](https://user-images.githubusercontent.com/11055362/49402111-d249a280-f6fd-11e8-91aa-ce92408621e8.png)

**Comment by EricDahlvang** [comment] 2018-12-03 23:52
@InsaneNaman Closing this as a duplicate of https://stackoverflow.com/questions/53584761/unable-to-save-kik-channel-configuration-azure-bot-service  

We will work internally to have the placeholder text updated for clarity.

**Closed by EricDahlvang** 2018-12-03 23:52 UTC
