### ISSUE TITLE
Bot not waiting for Prompts.text input and Prompts.choice  

### ISSUE THREAD

**Issue by vishmonne** [Microsoft/BotBuilder-V3#118] opened 2019-02-21 07:21 UTC
### Bot info:

•	SDK Platform : Node.js
•	SDK Version : v3
•	Deployment Environment : Azure Bot service 
•	3 Web app bot created in Azure ( dev, demo and prod)

### Issue Description:

builder.Prompts.choice and builder.Prompts.text  is not waiting for user input ( It sometimes wait for the user input and sometimes doesn’t wait and goes back to the main function and treat it as a separate utterance and goes to Luis ) in the prod environment

We were facing the same issue in the demo environment , where we had followed these steps in solving the issue.
•	We moved all the packages from dev to demo environment 
•	We moved all the code files again from dev to demo 
•	We restarted the app service 

We had followed the same steps in the prod environment but  we are not able to resolve the issue . 
We tried the same prod code in the local in visual studio code and tested it with  bot Emulator and it works completely fine.

### Behaviour Noticed: 
We noticed that whenever the bot URL link is opened , the connectorsetup.js file,  which connects with the bot is getting refreshed multiple times in azure.

### Code Example:

I am using this way to recognize the Luis in my code
 
```node
builder.LuisRecognizer.recognize(session.message.text, '<model url>', function (err, intents, entities) {
    if (entities) {
        var entity = builder.EntityRecognizer.findEntity(entities, 'TYPE');
        // do something with entity...
    }
});
```

### Things done from  my side

When i searched in git i got this solution in which they told to use on enable and solve the issue
Another example can be found here: [#2670 (comment)](https://github.com/Microsoft/BotBuilder/issues/2670#issuecomment-300275154)

```node
var recognizer = new builder.LuisRecognizer(LuisModelUrl)
    .onEnabled(function (context, callback) {
        // LUIS is only ON when there are no tasks pending(e.g. Prompt text) 
        var enabled = context.dialogStack().length === 0;
        callback(null, enabled);
    });
```

But the problem here was my way of calling the Luis is different and i am not sure how we can use onenabled function is builder.LuisRecognizer.recognize

**Comment by vishmonne** [comment] 2019-02-23 15:07
Hi Team,

Any solution for this issue ?

**Comment by vishmonne** [comment] 2019-02-25 10:53
Hi i think i am facing the same issue as  [#4477](url)

**Comment by v-kydela** [comment] 2019-02-25 19:18
The issue you linked to was fixed in BotBuilder 3.15.3. Have you updated your SDK to the latest version of v3?

Also, you should not be using in-memory storage for a published bot. Please have a look at the [documentation](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-state?view=azure-bot-service-3.0#manage-custom-data-storage) for some help implementing proper storage.

Looking at your code, it is a little strange to me that you're calling `session.endDialog()` twice:

```node
if (TopIntent != "None") {
    session.endDialog();
    myIntentHandler(session, session.message.text);
}
else if (TopIntent == "None") {
    noneSecondResp(session);
}

session.endDialog();
```

That's probably not directly related to your problem, though.

**Comment by vishmonne** [comment] 2019-02-26 17:58
Hi @v-kydela  thanks for replying back.

i was not able to update it to 3.15.3 it showed me this error (PFA THE Screenshot)
![error package](https://user-images.githubusercontent.com/10339913/53435047-e90e4580-3a1d-11e9-8b05-fe27a7ad3374.PNG)

Can u help me with why this error is coming and i am only able to update it to 3.16.0 , not other than that in SDK V3. And after i update it to 3.16.0 also the same issue exists.

I am using now a Manage state data using CosmosDB , thanks for updating that 

Looking forward in hearing from you @v-kydela

**Comment by v-kydela** [comment] 2019-02-26 19:34
Hi @vishmonne 

You can see that the output is saying that version 3.15.3 is not available. It shows you a list of valid install targets and 3.16.0 and 3.15.0 are there but not 3.15.3. You can also verify this by going here and clicking on [versions](https://www.npmjs.com/package/botbuilder).

This is fine because you don't need 3.15.3. I just said to update to the latest version, and 3.16.0 is sure to have all the fixes you need. There's no reason to downgrade.

Does using CosmosDB fix your problem?

**Comment by vishmonne** [comment] 2019-02-28 06:19
hi @v-kydela , when i implemented the CosmosDB, the prompts.text issue got resolved, but in the prompts.choice function i have a issue ( the same random types)

**Please see my code for the Prompts.choice**

`
var test = ""; //global variable 
function Prompt_With_Choice(session,Content,Buttons,intent,entity,entitytype)
{
    test=entity; 
    console.log("the test value is " + test ); // i am getting the value of test 
    session.beginDialog('Prompt_With_Choice', entityType_prompts);
}

bot.dialog('Prompt_With_Choice', [
   
    function (session) {
        console.log("the test value is " + test ); // i am getting the value of test 
        builder.Prompts.customize(builder.PromptType.choice, new builder.PromptChoice({minScore: 1.0}));
        builder.Prompts.choice(session,content_prompts,buttons_prompts,{listStyle:builder.ListStyle.button,maxRetries: 0});
    },
    function (session, results) {

         console.log("the test value is " + test ); // i am not getting the value of test, its showing empty 
        if(results.response)
        {
        
            var lowerentity=results.response.entity;
            session.endDialog();
        }
        else
        {
            session.sendTyping();
            session.endDialog();
            a.myIntentHandler(session, session.message.text);
        }
          
    }
]
);

`

**Comment by v-kydela** [comment] 2019-03-01 01:25
Hi @vishmonne 

That is actually expected behavior and it's a good example of why bots need state storage. When deployed, your bot may be running on many different servers. When you send a message to your bot, there's no telling what machine will receive that message. Therefore there's no reason to expect the bot's local variables to have the same locally-stored data that they did on the last turn. The best way to conceptualize how a bot works is to assume your bot has shut down and then restarted between each turn so that each turn is handled by a totally different instance of your bot application. This [article](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-state?view=azure-bot-service-4.0) from the V4 documentation may help you understand state better. If you want a variable like `test` to persist between turns, you'll need to store it in your bot's [state](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-state?view=azure-bot-service-3.0).

Does this resolve your issue?

**Comment by vishmonne** [comment] 2019-03-04 12:40
hi @v-kydela , thanks for the detailed update on this,  i read through the link and got to understand better on the bot's state . By doing that , solved my random issue. 

 But i wanted to know how come the same code with the memory storage as inMemory is working correctly in another web app bot , but not in this ?

**Comment by v-kydela** [comment] 2019-03-04 17:37
It's very difficult to answer that without more information. Here are some possibilities:

1. Maybe it is only working randomly and so you just happened to not have seen it fail yet
2. Maybe you're using a different version of the BotBuilder SDK that handles state differently
3. Maybe you're using different code that doesn't depend on state in the same way
4. Maybe you're uploading the bot to a server that doesn't scale sideways
5. Maybe you're not uploading it at all and just testing locally

Does this resolve your issue?

**Comment by v-kydela** [comment] 2019-03-08 00:05
@vishmonne - Do you still need help?

**Comment by vishmonne** [comment] 2019-03-08 07:32
Hi @v-kydela , i am fine with the explanation. Thanks a lot for helping around with the random button issues. Really appreciate the help. We can close this issue.

**Closed** 2019-03-08 17:27 UTC
