### ISSUE TITLE
High memory usage when using FormFlow JSON schema.

### ISSUE THREAD

**Issue by chyonek** [Microsoft/BotBuilder-V3#74] opened 2018-11-21 00:49 UTC
## Version
Microsoft.Bot.Builder.FormFlow.Json

3.15.2 Not repro
3.15.2.3 Not repro
3.15.3 Repro
...
3.17.0.42969 Repro

## Describe the bug
High memory usage occurs in the sample of Annotated Sandwich Bot when using FormFlow JSON schema.
Every time I answer the question written in JSON, the memory usage increases about 100 MB. OutOfMemoryException occurred in my customer's environment.

## To Reproduce
1. Open this sample in Visual Studio 2017.
AnnotatedSandwichBot
https://github.com/Microsoft/BotBuilder-V3/tree/master/CSharp/Samples/AnnotatedSandwichBot

2. Change the code. 
![code](https://user-images.githubusercontent.com/41774106/48811551-aa5b5600-ed71-11e8-8828-f7a7ff4c560f.PNG)

3. Click 'Start Debugging'
4. Talk with bot using emulator and see memory window

## Expected behavior
Stable memory usage
![memory](https://user-images.githubusercontent.com/41774106/48811663-22c21700-ed72-11e8-9bc3-859f5eebdad8.png)

## Additional context
Compare of botbuilder@3.15.2.0 and botbuilder@3.15.3.0
https://github.com/Microsoft/BotBuilder-V3/compare/botbuilder@3.15.2.0...botbuilder@3.15.3.0

I think this change is the cause of this issue.
https://github.com/Microsoft/BotBuilder-V3/commit/4fbea59c57cece4e26c609c175e7d378784988ec

Since OrderBy method has poor memory efficiency, I think that high memory usage is occurring as the following discussion.

How to avoid OrderBy - memory usage problems
https://stackoverflow.com/questions/3329985/how-to-avoid-orderby-memory-usage-problems

[bug]
[dotnet]

**Comment by EricDahlvang** [comment] 2018-11-22 00:50
Hi @chyonek 

Thank you for reporting this.  This change appears to be the cause of the memory issues: https://github.com/Microsoft/BotBuilder-V3/commit/c78b7d8c93560dffbffc43acccbdcf923fc71504

This was introduced to fix https://github.com/Microsoft/BotBuilder/issues/4755  However, it is apparently doing too much.

Commenting out these lines that clear the _scripts in the FormBuilderJson restores the normal memory consumption for Annotated Sandwich Bot.

```js
public FormBuilderJson(JObject schema)
        {
            _schema = schema;
            //lock (_scripts)
            //{
            //    _scripts.Clear();
            //}
            ProcessOptions();
            ProcessOnCompletion();
        }
```

This PR https://github.com/Microsoft/BotBuilder-V3/pull/76 will revert c78b7d8c93560dffbffc43acccbdcf923fc71504

**Comment by ms-yuhara** [comment] 2018-11-22 07:48
Thank you @EricDahlvang

I have confirmed that memory consumption can be suppressed by the above code change as well in my environment.
However, if we revert this, the original #4755 problem will reoccur, won't it?

**Comment by EricDahlvang** [comment] 2018-11-22 16:30
Yes, but the original problem was related to a bad script being present.  It isn't a valid fix to recreate all of the scripts every time the dialog loads.

**Comment by CoHealer** [comment] 2018-11-27 17:47
Fix has been reviewed and checked in. Will close this upon the next v3 publish.

**Comment by CoHealer** [comment] 2018-12-06 19:03
Fix checked in & merged into master.

**Closed by CoHealer** 2018-12-06 19:03 UTC
Labels: bug

**Comment by chyonek** [comment] 2018-12-07 00:33
I am grateful for your speedy response.
