### ISSUE TITLE
[v3.15.0][Messenger] Sending a Carousel Message with Hero Cards shows the cards in a random order not like the attachments array order

### ISSUE THREAD

**Issue by SalehAlbuga** [Microsoft/BotBuilder-V3#121] opened 2019-03-02 21:47 UTC
## Version
3.15.0

## Describe the bug
In FB Messenger, sending a Carousel Message with Hero Cards shows the cards in a random order not like the attachments array order.
My code looks like this
```node
var msg = new builder.Message(session)
	.attachmentLayout(builder.AttachmentLayout.carousel)
	.attachments(data.arr);
	
session.send('What do you feel like today?');

builder.Prompts.choice(session, msg, data.choices, {
	maxRetries: 0
});
```
I can't get it to show the cards in the same order in the array! Which is extremely annoying for users especially that my client shows their menu in a certain order!
*arr* is being returned from the database, I verified that it is in the right order before being passed to attachments(_)

## Expected behavior
Show the cards in the same order as the array passed

[bug]
[javascript]

**Comment by v-kydela** [comment] 2019-03-04 21:41
Hi @SalehAlbuga 

What Messenger client are you using?

**Comment by Zhashkha** [comment] 2019-03-05 07:04
Same to me
SDK Platform: .NET
SDK Version: 3.16.0
Active Channels: Facebook
Deployment Environment: Azure Bot Service, Azure App Service

**Comment by v-kydela** [comment] 2019-03-05 19:52
@SalehAlbuga 
@Zhashkha 

I have just reproduced this issue extensively myself. The Facebook Messenger platform has its own card system called [templates](https://developers.facebook.com/docs/messenger-platform/send-messages/template/generic/#carousel) that can accessed directly using an activity's [channel data](https://blog.botframework.com/2017/03/28/custom-channel-data/). However, the issue persists whether I use a Facebook Messenger payload directly or whether I send a Bot Framework card and let the connector handle it.

It appears to be caused by a change on the Facebook side. There are bug reports that are not limited to the Bot Framework: https://developers.facebook.com/support/bugs/2310937235657679

I am closing this issue because there is nothing we can do from our end, but I hope Facebook fixes this soon.

**Closed by v-kydela** 2019-03-05 19:52 UTC

**Comment by SalehAlbuga** [comment] 2019-03-11 20:39
@v-kydela Thank you very much for the response! I'm using iOS Facebook Messenger

**Comment by SalehAlbuga** [comment] 2019-03-11 20:41
According to Facebook this has been fixed and I can confirm they are showing in the right order now!
