### ISSUE TITLE
Hostname/IP does not match certificate's altnames

### ISSUE THREAD

**Issue by OksanaBerdnik** [microsoft/BotBuilder-V3#168] opened 2019-10-28 17:23 UTC
## Version
"botbuilder": "^3.16.0",
"botbuilder-azure": "^3.1.0",

## Describe the bug
I've received this error: 
```
Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: facebook.botframework.com. is not in the cert's altnames: DNS:*.azurewebsites.net, DNS:*.scm.azurewebsites.net, DNS:*.azure-mobile.net, DNS:*.scm.azure-mobile.net, DNS:*.sso.azurewebsites.net
    at Object.checkServerIdentity (tls.js:241:17)
    at TLSSocket.onConnectSecure (_tls_wrap.js:1132:27)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket._finishInit (_tls_wrap.js:625:8)
```
Any suggestions would be greatly appreciated

## To Reproduce
Send any data throught a bot

## Expected behavior
Everything works smoothly

This is an unexpected error, everything used to work well till Thursday (24.10.19)

[bug]
[javascript]

**Comment by mdrichardson** [comment] 2019-10-29 16:29
@OksanaBerdnik How is your bot hosted? If it's in Azure, can you go to `Azure Portal > Your Resource Group > Your App Service > TLS/SSL Settings` and ensure that TLS 1.2 is enabled and everything else looks like this:

![image](https://user-images.githubusercontent.com/40401643/67787844-7cc16700-fa2e-11e9-84df-0e1621ae5582.png)

I haven't seen this error before, but it recently became required to use TLS 1.2, so I'm guessing it's related to that. If not, please provide:

* How your bot is hosted
* Your appId
* Whether or not Test in Web Chat works
* Which channels are or are not working

**Comment by hex-344505** [comment] 2019-10-30 09:22
the case is that one request gives valid certificate and another - not correct
same curl request return 
* SSL: no alternative certificate subject name matches target host name 'facebook.botframework.com'
and 
* Server certificate:
*  subject: CN=*.botframework.com
*  start date: Jun 10 20:07:48 2019 GMT
*  expire date: Jun 10 20:07:48 2020 GMT
*  subjectAltName: host "facebook.botframework.com" matched cert's "*.botframework.com"
*  issuer: C=US; ST=Washington; L=Redmond; O=Microsoft Corporation; OU=Microsoft IT; CN=Microsoft IT TLS CA 4
*  SSL certificate verify ok.

in same time facebook.botframework.com have only one IP address, so it behind balancer or something else

**Comment by OksanaBerdnik** [comment] 2019-10-30 10:00
Attachments to previous comment: 

In case certificate is valid:
![download (2)](https://user-images.githubusercontent.com/15250529/67847218-1fe7ae80-fb0b-11e9-809f-5d0d9cf3401e.png) 

In case the certificate is not matched (the same curl):
![download](https://user-images.githubusercontent.com/15250529/67847274-3f7ed700-fb0b-11e9-9efa-cfa2ac515de3.png)

Host:
![download (1)](https://user-images.githubusercontent.com/15250529/67847282-41489a80-fb0b-11e9-9cd2-87d612066d27.png) 

* How your bot is hosted
The bots are hosted on our servers, not in Azure App Service.
* Your appId
81834727-3b91-4e58-9816-49b8a13ee59b
* Whether or not Test in Web Chat works
In Web Chat bot works fine
* Which channels are or are not working
Facebook Channel

This error occurs from time to time but often

**Comment by OksanaBerdnik** [comment] 2019-10-30 10:18
@mdrichardson Attachments to previous comment: 

In case certificate is valid:
![download (2)](https://user-images.githubusercontent.com/15250529/67847218-1fe7ae80-fb0b-11e9-809f-5d0d9cf3401e.png) 

In case the certificate is not matched (the same curl):
![download](https://user-images.githubusercontent.com/15250529/67847274-3f7ed700-fb0b-11e9-9efa-cfa2ac515de3.png)

Host:
![download (1)](https://user-images.githubusercontent.com/15250529/67847282-41489a80-fb0b-11e9-9cd2-87d612066d27.png) 

* How your bot is hosted
The bots are hosted on our servers, not in Azure App Service.
* Whether or not Test in Web Chat works
In Web Chat bot works fine
* Which channels are or are not working
Facebook Channel

This error occurs from time to time but often

**Comment by mdrichardson** [comment] 2019-10-30 15:51
@hex-344505 @OksanaBerdnik Thank you for the additional info! Can you try **deleting** (not disable, but delete) and then re-add your Facebook channel from `Azure Portal > Your Resource Group > Your Web App Bot/Bot Channels Registration > Channels`?

**Comment by OksanaBerdnik** [comment] 2019-10-30 16:33
I've deleted the channel and re-added it. But it doesn't work for me

**Comment by mdrichardson** [comment] 2019-10-30 16:41
@OksanaBerdnik Alright. It was sort of a hail mary before I rope in some other folks to assist. I'm reaching out to see if one of our instances hosting facebook.botframework.com has an invalid cert. I will update this issue once I find the cause.

**Comment by mdrichardson** [comment] 2019-10-30 18:05
@hex-344505 @OksanaBerdnik 

I tried that curl command ~100 times and all were successful. We're also seeing that all of the certs are valid on the ~10 instances running `facebook.botframework.com`.

Can you try running `nslookup facebook.botframework.com`?

The output should be something like:

```bash
$> nslookup facebook.botframework.com
Server:  f5-2.redmond.corp.microsoft.com
Address:  10.50.10.50

 

Non-authoritative answer:
Name:    waws-prod-bay-051.cloudapp.net
Address:  40.78.18.232
Aliases:  facebook.botframework.com
          bc-facebook.trafficmanager.net
          bc-facebook-westus.azurewebsites.net
          waws-prod-bay-051.vip.azurewebsites.windows.net
```

Can you then run `curl -v <HOST>`, where <HOST> is the equivalent in your output to `bc-facebook-westus.azurewebsites.net`, above?

**Comment by OksanaBerdnik** [comment] 2019-10-30 18:31
```
curl -v https://facebook.botframework.com/api/v1/bots/****

*   Trying 40.89.131.148...
* Connected to facebook.botframework.com (40.89.131.148) port 443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 592 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_256_GCM_SHA384
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* SSL: certificate subject name (*.azurewebsites.net) does not match target host name 'facebook.botframework.com'
* Closing connection 0
curl: (51) SSL: certificate subject name (*.azurewebsites.net) does not match target host name 'facebook.botframework.com'


nslookup facebook.botframework.com

Server:		127.0.1.1
Address:	127.0.1.1#53

Non-authoritative answer:
facebook.botframework.com	canonical name = bc-facebook.trafficmanager.net.
bc-facebook.trafficmanager.net	canonical name = bc-facebook-par.azurewebsites.net.
bc-facebook-par.azurewebsites.net	canonical name = waws-prod-par-003.sip.azurewebsites.windows.net.
waws-prod-par-003.sip.azurewebsites.windows.net	canonical name = waws-prod-par-003.cloudapp.net.
Name:	waws-prod-par-003.cloudapp.net
Address: 40.89.131.148
```

**Comment by mdrichardson** [comment] 2019-10-30 19:12
This is becoming quite the head-scratcher. By any chance, can you visit `dev.botframework.com` and ensure that you trust the certificate there:

![image](https://user-images.githubusercontent.com/40401643/67890732-7aced500-fb0e-11e9-858b-176d204b9c39.png)

**Comment by hex-344505** [comment] 2019-10-31 08:33
> I tried that curl command ~100 times and all were successful. We're also seeing that all of the certs are valid on the ~10 instances running `facebook.botframework.com`.

Counter 20
*  subjectAltName: host "facebook.botframework.com" matched cert's "*.botframework.com"
Thu, 31 Oct 2019 10:25:51 +0200
Counter 21
*  subjectAltName does not match facebook.botframework.com
* SSL: no alternative certificate subject name matches target host name 'facebook.botframework.com'
curl: (60) SSL: no alternative certificate subject name matches target host name 'facebook.botframework.com'
Thu, 31 Oct 2019 10:25:51 +0200
Counter 22
*  subjectAltName: host "facebook.botframework.com" matched cert's "*.botframework.com"

Thu, 31 Oct 2019 10:25:53 +0200
Counter 35
*  subjectAltName: host "facebook.botframework.com" matched cert's "*.botframework.com"
Thu, 31 Oct 2019 10:25:53 +0200
Counter 36
*  subjectAltName does not match facebook.botframework.com
* SSL: no alternative certificate subject name matches target host name 'facebook.botframework.com'
curl: (60) SSL: no alternative certificate subject name matches target host name 'facebook.botframework.com'
Thu, 31 Oct 2019 10:25:54 +0200
Counter 37
*  subjectAltName: host "facebook.botframework.com" matched cert's "*.botframework.com"

this is output of simple script
#!/bin/bash
for i in {1..100}
do
   date -R >> request.txt
   echo "Counter $i" >> request.txt
   curl -v https://facebook.botframework.com 2>&1 | grep match >> request.txt
done

NSLOOKUP
nslookup facebook.botframework.com
Non-authoritative answer:
Name:	waws-prod-par-003.cloudapp.net
Address: 40.89.131.148

hexus@devops:~$ nslookup dev.botframework.com
Non-authoritative answer:
Name:	waws-prod-par-001.cloudapp.net
Address: 52.143.137.150

same resolving i get from googles dns (8.8.8.8)

**Comment by OksanaBerdnik** [comment] 2019-10-31 09:14
@mdrichardson The certificate is valid on dev.botframework.com.
Previously I've run curl from on AWS node or on the local machine but from Azure console, it works fine

```$ curl -v https://facebook.botframework.com/api/v1/bots/****
*   Trying 40.118.29.72...
* Connected to facebook.botframework.com (40.118.29.72) port 443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 594 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_256_GCM_SHA384
*        server certificate verification OK
*        server certificate status verification SKIPPED
*        common name: *.botframework.com (matched)
*        server certificate expiration date OK
*        server certificate activation date OK
*        certificate public key: RSA
*        certificate version: #3
*        subject: CN=*.botframework.com
*        start date: Mon, 10 Jun 2019 20:07:48 GMT
*        expire date: Wed, 10 Jun 2020 20:07:48 GMT
*        issuer: C=US,ST=Washington,L=Redmond,O=Microsoft Corporation,OU=Microsoft IT,CN=Microsoft IT TLS CA 4
*        compression: NULL
* ALPN, server did not agree to a protocol
> GET /api/v1/bots/**** HTTP/1.1
> Host: facebook.botframework.com
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Cache-Control: no-cache
< Pragma: no-cache
< Expires: -1
< Server: Microsoft-IIS/10.0
< x-ms-request-id: |384d0b77cd4c0041aa976b83b5716c2e.bc782601_
< Strict-Transport-Security: max-age=31536000
< Date: Thu, 31 Oct 2019 08:19:24 GMT
< Content-Length: 0
<
* Connection #0 to host facebook.botframework.com left intact
```
When I try to visit Manage page to generate app password I receive 404, please see screenshot below (it`s related to all apps, not only new one):
![image](https://user-images.githubusercontent.com/15250529/67933772-2dff0300-fbcf-11e9-8b31-754f92f4c893.png)

**Comment by hex-344505** [comment] 2019-10-31 15:03
above script from AWS instance eu-west-3 zone - every 10th request give error
same script on EC2 in u-west-1 1000 requests - no errors
I have no idea what happens :(

**Comment by mdrichardson** [comment] 2019-10-31 16:22
@OksanaBerdnik @hex-344505 I was finally able to repro this by VPN-ing to Paris and running that script. I'll dig into this further.

@OksanaBerdnik Regarding that 404. Where is that bot hosted? I've seen that happen occasionally if your bot is hosted off of Azure. You *should* be able to access the app registration by going directly to the [App Registration page](https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationsListBlade) or `https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationMenuBlade/Overview/appId/<yourAppId>/isMSAApp/` if that doesn't work.

**Comment by OksanaBerdnik** [comment] 2019-10-31 18:20
@mdrichardson All our bots are hosted on our servers, not in Azure App Service. Regarding that 404: App Registration page has helped me, thank you! But regarding your advice to host our bot on Azure portal: are there other ways to solve this issue?

**Comment by mdrichardson** [comment] 2019-10-31 18:25
@OksanaBerdnik Regarding hosting off-Azure:

I don't believe this affects the 404, as I'm able to repro through VPN on the same machine that works without VPN. We'll dig into what's going on and let you know as soon as we do.

The only issue we've talked about that you'll continue to have while hosting yourself is accessing the App Registration via the Web App Bot. I believe the Azure Bot Services team is aware of this, but it's a low-priority issue.

So, with all that said, I don't necessarily advise that you host on Azure since I don't believe it will fix this issue.

If you're looking for a temporary workaround, you might try migrating your servers to a West US instance, if you can--that's where I am and where I'm unable to repro.

Again, though, we'll look into this and see if we can get it fixed.

**Comment by mdrichardson** [comment] 2019-11-01 16:32
@OksanaBerdnik @hex-344505 Are you guys still able to repro this? I VPN'd to Paris again this morning and had the script run 4,000 times (not exaggerating). All of them were successful.

**Comment by mdrichardson** [comment] 2019-11-04 21:22
@OksanaBerdnik @hex-344505 Are you still able to repro this? I just tested from Paris and was successful for 200 of 200 requests.

If not, please [capture a System.NET trace](SSLValidation) and paste the contents of `networktrace.txt`.

**Comment by mdrichardson** [comment] 2019-11-07 16:05
@OksanaBerdnik @hex-344505 Were you able to re-test this? There's a couple of different teams looking into this and none of us can reproduce the error any more.

**Comment by OksanaBerdnik** [comment] 2019-11-07 16:34
@mdrichardson Today we've reproduced this bug on AWS instance located in Paris

**Comment by mdrichardson** [comment] 2019-11-07 17:20
@OksanaBerdnik Understood. I can't seem to repro this any more, but we'll continue looking into this.

**Comment by hex-344505** [comment] 2019-11-07 17:33
> @OksanaBerdnik Understood. I can't seem to repro this any more, but we'll continue looking into this.

you know, i think that i can prepare an instance for testing , if it will be suitable for you - let me know

by the way , we also repro this bug even from our local ISP.

**Comment by mdrichardson** [comment] 2019-11-07 17:34
@hex-344505 That would likely help, if you're able to. Feel free to send details to me via email, if you'd prefer: vDASHmicricATmicrosoftDOTcom (replace all-caps with appropriate character).

**Comment by hex-344505** [comment] 2019-11-07 18:07
> @hex-344505 That would likely help, if you're able to. Feel free to send details to me via email, if you'd prefer: vDASHmicricATmicrosoftDOTcom (replace all-caps with appropriate character).

sent you an email, thanks in advance

**Comment by mdrichardson** [comment] 2019-11-07 18:31
@hex-344505 I was able to SSH in and verify this still occurs for you. Still looking into things. I believe it's something the Azure team will need to fix.

**Comment by hex-344505** [comment] 2019-11-07 18:33
we have mail from azure team that they fix it but issue still exist :(

**Comment by mdrichardson** [comment] 2019-11-07 18:35
We’ve got a couple of separate issues still open and tracking this. I’m guessing that one got sent to you that it was fixed because they asked me to repro and I couldn't, then we didn't hear from you that it was still an issue. They're still open and being worked on, however.

I can give these other teams access, if you'd like.

**Comment by hex-344505** [comment] 2019-11-07 18:44
> I can give these other teams access, if you'd like.
it will be great.
and i updated support request.
Thanks

**Comment by mdrichardson** [comment] 2019-11-08 21:09
@OksanaBerdnik @hex-344505 Azure reps are reporting they fixed one of their front end webservers and the issue should be fixed. Are you able to reproduce it, now?

**Comment by hex-344505** [comment] 2019-11-09 07:54
> @OksanaBerdnik @hex-344505 Azure reps are reporting they fixed one of their front end webservers and the issue should be fixed. Are you able to reproduce it, now?

looks like they fix it. i cant reproduce error :)
Thanks ! your save our bot :)

**Comment by mdrichardson** [comment] 2019-11-11 16:11
Good to hear!

**Closed by mdrichardson** 2019-11-11 16:11 UTC
Labels: Bot Services, customer-replied-to, customer-reported

**Comment by vohuythao** [comment] 2021-05-26 08:54
Hello guys,

Today we met exactly this problem.

I try to curl -v https://api.tryemanagecrm.com

And in 100 times, we got around 20 times with this error

Trying 51.143.102.21:443...
* Connected to api.tryemanagecrm.com (51.143.102.21) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=*.azurewebsites.net
*  start date: Sep 28 19:00:01 2020 GMT
*  expire date: Sep 28 19:00:01 2021 GMT
*  subjectAltName does not match api.tryemanagecrm.com
* SSL: no alternative certificate subject name matches target host name 'api.tryemanagecrm.com'
* Closing connection 0
* TLSv1.2 (OUT), TLS alert, close notify (256):
curl: (60) SSL: no alternative certificate subject name matches target host name 'api.tryemanagecrm.com'
More details here: https://curl.haxx.se/docs/sslcerts.html

We use Azure App Service with Traffic Manager

Any hints to help us solve this?
Thank you very much

**Comment by mdrichardson** [comment] 2021-05-26 15:10
@vohuythao I'm assuming `api.xxxx.com` is the domain for your App Service? If so, it would be best to open a ticket for this through Azure support, since this is more of a service issue and less of a code one.

**Comment by vohuythao** [comment] 2021-05-27 01:51
Hello @mdrichardson 
Thank you for the reply
Yes, that is correct, it is our App Service.
I also open a ticket for Azure support.
I will update there if there is any solutions from Azure support

Thank you

**Comment by vohuythao** [comment] 2021-06-03 10:32
Hello guys,

I have fixed this by replace another SSL certificates.

The one from GoDaddy, has some problem.
I replace with the one from Digicert and it is ok now
